title: "Your Academic Site"
description: "Lectures and Articles"
locale: "en-US"

# Enable Arabic/Urdu support
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Language settings
defaults:
  - scope:
      path: "arabic"
    values:
      lang: "ar"
      dir: "rtl"
  - scope:
      path: "urdu" 
    values:
      lang: "ur"
      dir: "rtl"
